;!knitout-2
;;Carriers: 6
inhook 6
tuck - f60 6
tuck - f58 6
tuck - f56 6
tuck - f54 6
tuck - f52 6
tuck - f50 6
tuck - f48 6
tuck - f46 6
tuck - f44 6
tuck - f42 6
tuck - f40 6
tuck - f38 6
tuck - f36 6
tuck - f34 6
tuck - f32 6
tuck - f30 6
tuck - f28 6
tuck - f26 6
tuck - f24 6
tuck - f22 6
tuck - f20 6
tuck - f18 6
tuck - f16 6
tuck - f14 6
tuck - f12 6
tuck - f10 6
tuck - f8 6
tuck - f6 6
tuck - f4 6
tuck - f2 6
releasehook 6
outhook 6
