;!knitout-2
;;Carriers: 6
inhook 6
stitch 20 25
tuck - f59 6
tuck - f55 6
tuck - f51 6
tuck - f47 6
tuck - f43 6
tuck + f41 6
tuck + f45 6
tuck + f49 6
tuck + f53 6
tuck + f57 6
tuck - b60 6
tuck - b56 6
tuck - b52 6
tuck - b48 6
tuck - b44 6
tuck - b40 6
tuck + b42 6
tuck + b46 6
tuck + b50 6
tuck + b54 6
tuck + b58 6
releasehook 6
knit - f59 6
knit - f57 6
knit - f55 6
knit - f53 6
knit - f51 6
knit - f49 6
knit - f47 6
knit - f45 6
knit - f43 6
knit - f41 6
knit + b40 6
knit + b42 6
knit + b44 6
knit + b46 6
knit + b48 6
knit + b50 6
knit + b52 6
knit + b54 6
knit + b56 6
knit + b58 6
knit + b60 6
knit - f59 6
knit - f57 6
knit - f55 6
knit - f53 6
knit - f51 6
knit - f49 6
knit - f47 6
knit - f45 6
knit - f43 6
knit - f41 6
knit + b40 6
knit + b42 6
knit + b44 6
knit + b46 6
knit + b48 6
knit + b50 6
knit + b52 6
knit + b54 6
knit + b56 6
knit + b58 6
knit + b60 6
xfer f59 b59
rack -2

